# Generated by Django 3.2 on 2023-05-12 05:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, verbose_name='Пол')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=6, verbose_name='Группа крови')),
                ('is_workless', models.BooleanField(null=True, verbose_name='Безработный')),
                ('is_married', models.BooleanField(verbose_name='В браке')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('registered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.residence')),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='tenant',
            field=models.ManyToManyField(through='people.ResidenceTenant', to='people.Person'),
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('finish', models.DateField(blank=True, null=True)),
                ('person_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriage_1', to='people.person')),
                ('person_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriage_2', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, person_1=django.db.models.expressions.F('person_2')), name='check_persons'),
        ),
    ]
