# Generated by Django 3.2 on 2023-05-12 05:58

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marriage',
            name='check_persons',
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, person_1=django.db.models.expressions.F('person_2')), name='No self'),
        ),
    ]
